name: moon
description: Moon
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  go_router: ^14.2.1
  equatable: ^2.0.5
  flutter_gen: any
  intl_utils: ^2.7.0
  get_it: ^7.6.4
  overlay_support: ^2.1.0
  gap: ^3.0.1
  sidebarx: ^0.17.1
  custom_sliding_segmented_control: ^1.8.3
  flutter_svg: 2.0.9
  animated_tree_view: ^2.3.0
  # fl_chart: ^0.69.0
  # syncfusion_flutter_charts: ^27.1.51
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  dotted_border: ^2.1.0
  loading_animation_widget: ^1.2.1


  template:
    path: ../../packages/template
  network:
    path: ../../packages/network
  auth:
    path: ../../packages/auth

dependency_overrides:



dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner:
  mockito: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner:
flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    # - assets/lotties/
